### ISSUE TITLE
No module named 'utils'

### ISSUE THREAD

**Issue by 13604249613** [TANGhz17/Regularbackup#6]
from utils.rtext import *
ModuleNotFoundError: No module named 'utils'

**Comment by 13604249613** [comment]
cant use pip to install:
ERROR: Could not find a version that satisfies the requirement utils.rtext (from versions: none)
ERROR: No matching distribution found for utils.rtext

**Comment by 13604249613** [comment]
[MCDR] [15:38:13] [TaskExecutor/ERROR]: 插件 SoloPlugin[file=Regularbackup.py,path=plugins\Regularbackup.py,state=PluginState.LOADING] 加载失败
Traceback (most recent call last):
  File "C:\Users\zhuda\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 175, in __load_plugin
    plugin.load()
  File "C:\Users\zhuda\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 98, in load
    self.__do_load()
  File "C:\Users\zhuda\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 93, in __do_load
    self._on_load()
  File "C:\Users\zhuda\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\type\solo_plugin.py", line 48, in _on_load
    self._load_entry_instance()
  File "C:\Users\zhuda\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\type\regular_plugin.py", line 66, in _load_entry_instance
    self.entry_module_instance = self._import_entrypoint_module()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhuda\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\type\solo_plugin.py", line 40, in _import_entrypoint_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\mcdr\plugins\Regularbackup.py", line 7, in <module>
    from utils.rtext import *
ModuleNotFoundError: No module named 'utils'

**Comment by wpcwzy** [comment]
惊了，这么老的插件竟然还有人用
这个插件已经很久没有维护了，不太建议继续使用。这两天我试着解决一下，看报错像是MCDR版本更新之后不再提供utils模块了
